slice_name: Patient Analytics Query Chart V5
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 16__table
  viz_type: table
  slice_id: 22
  query_mode: raw
  groupby: []
  time_grain_sqla: P1D
  temporal_columns_lookup:
    Date de visite: true
    Date de naissance: true
  metrics: []
  all_columns:
  - ID de visite
  - Date de visite
  - Lieu d'accueil
  - Lieu de consultation
  - Lieux de soins
  - Médecin traitant
  - ID du patient
  - Prénom
  - Nom
  - CNI Burundi
  - Ancien ID (Legacy ID)
  - ID OpenMRS
  - Acte de naissance
  - Date de naissance
  - Âge
  - Sexe
  - Chef de ménage
  - Province
  - Commune
  - Zone
  - Colline
  - Type de cas
  - Type de consultation
  - Catégorie de maladie
  - Grossesse
  - Motifs de consultation
  - Liste des rencontres
  - Nombre de rencontres
  - Liste des diagnostics
  - Nombre de diagnostics
  - Liste des diagnostics confirmés
  - Nombre de diagnostics confirmés
  - Liste des examens de laboratoire
  - Nombre d'examens de laboratoire
  - Coût des examens de laboratoire
  - Liste des procédures
  - Nombre de procédures
  - Coût des procédures
  - Liste des médicaments
  - Nombre de médicaments
  - Prescripteur(s)
  - Coût des médicaments
  - Montant de la facture
  - Assurance
  - Assurance complémentaire
  - Taux de couverture
  - Liste de prix Odoo
  percent_metrics: []
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: Date de visite
  order_by_cols: []
  row_limit: 50000
  server_page_length: 10
  order_desc: true
  table_timestamp_format: smart_date
  page_length: 0
  include_search: true
  show_cell_bars: false
  align_pn: true
  color_pn: true
  conditional_formatting: []
  extra_form_data: {}
  dashboards:
  - 4
  granularity_sqla: Date de visite
query_context: null
cache_timeout: null
uuid: 5b123b21-5f12-4e32-9709-dc0943db97e3
version: 1.0.0
dataset_uuid: 82eb0545-483b-4e7d-b4de-a38eac66ea25
