slice_name: Services – Rencontres par service, type et lieu
description: null
certified_by: null
certification_details: null
viz_type: pivot_table_v2
params:
  datasource: 70__table
  viz_type: pivot_table_v2
  groupbyRows:
  - service
  - encounter_type
  - location
  groupbyColumns: []
  metrics:
  - encounters
  - patients
  metricsLayout: COLUMNS
  adhoc_filters:
  - clause: WHERE
    subject: encounter_datetime
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  row_limit: 10000
  order_desc: true
  aggregateFunction: Sum
  valueFormat: SMART_NUMBER
  date_format: '%Y-%m'
  rowOrder: key_a_to_z
  colOrder: key_a_to_z
  rowTotals: true
  colTotals: true
  rowSubTotals: false
  colSubTotals: false
  transposePivot: false
  combineMetric: false
query_context: null
cache_timeout: null
uuid: 4eb0813f-041c-45b8-f6f3-e2815a0bd34f
version: 1.0.0
dataset_uuid: 1b8d5e0c-d1e9-4285-c3c0-bf5e27d8a01c
