slice_name: Total lab tests ordered
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 100__table
  viz_type: big_number_total
  slice_id: 31
  metric: count
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_lab_orders_time_21
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    operatorId: TEMPORAL_RANGE
    sqlExpression: null
    subject: date_activated
  header_font_size: 0.4
  subheader_font_size: 0.15
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  extra_form_data: {}
  dashboards: []
query_context: null
cache_timeout: null
uuid: 78856005-b9bc-4132-9cca-346f5f3083b5
version: 1.0.0
dataset_uuid: 704ef6ec-bc69-4ac0-8e6f-e5da5d31c129
