slice_name: "Usage \u2013 Orders per Type per Week"
description: null
certified_by: null
certification_details: null
viz_type: pivot_table_v2
params:
  datasource: 40__table
  viz_type: pivot_table_v2
  groupbyRows:
  - service
  groupbyColumns:
  - activity_datetime
  temporal_columns_lookup:
    activity_datetime: true
  time_grain_sqla: P1W
  metrics:
  - orders
  metricsLayout: COLUMNS
  adhoc_filters:
  - clause: WHERE
    subject: activity_datetime
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  - clause: WHERE
    subject: activity_kind
    operator: ==
    comparator: Order
    expressionType: SIMPLE
  row_limit: 10000
  order_desc: true
  aggregateFunction: Sum
  valueFormat: SMART_NUMBER
  date_format: smart_date
  rowOrder: key_a_to_z
  colOrder: key_a_to_z
  rowTotals: false
  colTotals: false
  rowSubTotals: false
  colSubTotals: false
  transposePivot: false
  combineMetric: false
query_context: null
cache_timeout: null
uuid: 6c7ca72e-4f76-4c2b-aef9-86619780f5bc
version: 1.0.0
dataset_uuid: c5df3d0c-fe8d-493c-a726-359d52972e1b
