slice_name: Weekly lab workload (tests ordered)
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 100__table
  viz_type: echarts_timeseries_bar
  slice_id: 25
  x_axis: date_activated
  time_grain_sqla: P1W
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - count
  groupby: []
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: date_activated
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: vertical
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  show_value: true
  only_total: true
  show_legend: false
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  y_axis_format: SMART_NUMBER
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards: []
query_context: null
cache_timeout: null
uuid: 9cd20a2e-f7b3-4cfa-b6fd-1d0f1f35299b
version: 1.0.0
dataset_uuid: 704ef6ec-bc69-4ac0-8e6f-e5da5d31c129
