services:
  openmrs:
    image: openmrs/openmrs-core:2.7.6
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-fsS",
          "--connect-timeout",
          "5",
          "--max-time",
          "10",
          "http://localhost:8080/openmrs/health/started",
        ]
      interval: 15s
      timeout: 10s
      retries: 40
      start_period: 600s

  keycloak:
    environment:
      KC_HOSTNAME_ADMIN_URL: ${SERVER_SCHEME}://${KEYCLOAK_HOSTNAME}
