services:
  openmrs:
    healthcheck:
      retries: 100
      test: ["CMD", "curl", "-f", "http://localhost:8080/openmrs"]
      interval: 10s
      timeout: 5s
      start_period: 30s
  keycloak:
    environment:
      KC_HOSTNAME_ADMIN_URL: ${SERVER_SCHEME}://${KEYCLOAK_HOSTNAME}
