name: CI

on:
  push:
    branches: ['main']
  release:
    types: [published]
  workflow_dispatch:

jobs:
  snapshot:
    if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') }}
    uses: ./.github/workflows/maven-publish.yml
    with:
      free-disk-space: true
      maven-args: '-Pbundled-docker'
    secrets:
      NEXUS_USERNAME: ${{ secrets.MAVEN_GITHUB_ACTIONS_DEPLOY_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.MAVEN_GITHUB_ACTIONS_DEPLOY_TOKEN }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_REGISTRY_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_REGISTRY_PASSWORD }}

  release:
    if: ${{ github.event_name == 'release' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/maven-publish.yml
    with:
      free-disk-space: true
      maven-args: '-Pbundled-docker -Pproduction'
    secrets:
      NEXUS_USERNAME: ${{ secrets.MAVEN_GITHUB_ACTIONS_DEPLOY_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.MAVEN_GITHUB_ACTIONS_DEPLOY_TOKEN }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_REGISTRY_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_REGISTRY_PASSWORD }}
